### PR TITLE
Allow for validation of the field via TextFormWidget

### PR DESCRIPTION
**Pull request by grahamsmith**
This PR allows for validation to be performed on the field. There are several use cases:

- Manual entry of the field needs to be validated as part of a form e.g. the field it empty.

- The provided phone number while valid is not one the application is looking for. e.g. wrong country code.

### CODE REVIEW

**Comment by grahamsmith** [comment]
@jaumard this is my last PR for the PhoneField :)

I am very unsure on the right approach here so feel free to school me on a better approach. I tried to extract the added value of the ask phone hint code to a composable approach so any field could be used and composed into something that works.

After 4 hours it felt overkill and in reality I imagine TextField and TextFormField are the most likely real world candidates.

**Comment by jaumard** [comment]
Yeah if we want to follow flutter's semantic we should have `PhoneFieldHint ` and `PhoneFormFieldHint `, I thinks that should be the cleaner solution... Because here `isFormWidget` is very fragile, because if it's false but you add a validator, this one is just ignored... at least if it's a different class it make it clear what the user want. What do you think ?

**Comment by grahamsmith** [comment]
Yes! This.

I wasn't overly happy with it but easier to get quick feedback and make improvements.

It feels like next step is to pull them apart and then see where/if we want to handle duplications.

**Comment by jaumard** [comment]
Might be enough to rename `PhoneFieldHint` to `_PhoneFieldHint` and have PhoneFieldHint and PhoneFormFieldHint setting that flag internally, like this no duplication and type is strong for external users

**Comment by grahamsmith** [comment]
gah missed this comment. I have created the two strong types. Would you be willing to take a look? You should be able to push to my PR as I have enabled edits by maintainers.

**Comment by grahamsmith** [comment]
Had a go, something like this?

```
class PhoneFormFieldHint extends StatelessWidget {
  final bool autofocus;
  final FocusNode focusNode;
  final TextEditingController controller;
  final List<TextInputFormatter> inputFormatters;
  final FormFieldValidator validator;
  final InputDecoration decoration;
  final TextField child;

  const PhoneFormFieldHint({
    Key key,
    this.child,
    this.controller,
    this.inputFormatters,
    this.validator,
    this.decoration,
    this.autofocus = false,
    this.focusNode,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return _PhoneFieldHint(key: key, 
        child: child, 
        inputFormatters: inputFormatters, 
        validator: validator, 
        decoration: decoration, 
        autofocus: autofocus, 
        focusNode: focusNode, 
        isFormWidget: true);
  }
}
```

**Comment by grahamsmith** [comment]
@jaumard just a heads up - I pushed a version that I *think* is what you were after

**Comment by jaumard** [comment]
LGTM yes :) thanks a lot!!

**Pull request merged**
